# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Wesley Reisz
tagline:          aut disce aut discede
url:              http://getpoole.com
highlighter:      pygments
paginate:         1
paginate_path:    "blog/page:num/"
baseurl:          /
author:
  name:           Wesley Reisz
  url:            https://twitter.com/wesreisz
  email:          wes@wesleyreisz.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/wesreisz
  
